### ISSUE TITLE
weather_at_place() fails with Reason: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by SamuelBachar** [csparpa/pyowm#107]
Hi is it only me or someone have same experience in last few days / hours ? 
Python 2.7 IDE : Visual Studio 2013  additional information

**Comment by csparpa** [comment]
Hi @SamuelBachar did you use the latest release? Please also make sure you use a dev API key

**Comment by SamuelBachar** [comment]
Hi i did used the latest release and i was using key in example ... Free
key for ppl who didnt payed already for api . I ll try that again once more
.

2016-05-16 9:54 GMT-07:00 Claudio Sparpaglione <notifications@github.com>:

**Comment by csparpa** [comment]
Can you pls confirm that this only happens when you call the `weather_at_place()` method and not for other ones?

The OWM API literally is a freak of nature, sometimes they just change it without any notice. I just want to figure out what happened on their side!

Thanks

**Comment by csparpa** [comment]
Ok @SamuelBachar I checked it out.

Basically, it's OK that you get that error, because you need to signup on the OpenWeatherMap website, obtain an API key from them and then use that key to instantiate PyOWM and make requests.

Because of the limitations of the "free" plan (as you can see here: https://home.openweathermap.org/subscriptions) I cannot embed a debug API key into the library.
