### ISSUE TITLE
UK, gives yesterday's day until 7am next day.

### ISSUE THREAD

**Issue by lardconcepts** [csparpa/pyowm#148]
It appears that "today" is still yesterday until about 7am.

I can see from https://openweathermap.desk.com/customer/en/portal/articles/1634438-time-format-and-zone that "OpenWeatherMap uses Unix time and UTC/GMT time zone for all API calls including current weather, forecast and historical data", so I'm not sure why it's still Sunday when it's Monday.

Using the site directly, it appears to be listing "yesterday" first, 

Has anyone encountered this before, and any ideas how to get round it? Thanks.

Here's a bit of the code I'm using... I think it's the "weatherday=" part that's going wrong for me...

```
def getWeatherByID(ID):
    obs = owm.weather_at_id(ID)
    l = obs.get_location()
    name = l.get_name()

    fc = owm.daily_forecast_at_id(ID, limit=3)
    f = fc.get_forecast()  
    w = obs.get_weather()

    for weather in f:
        weatherday=datetime.datetime.fromtimestamp(int(weather.get_reference_time())).strftime('%A')
        weatherstatus=weather.get_detailed_status()
```

**Comment by csparpa** [comment]
@lardconcepts I'm not sure I see your point...

Just to provide some context: when you call an OWM API endpoint you get data that is referred - as you stated - to a UNIX timestamp: this is referred to as `reference_time` in PyOWM, and means the point in time when the measurement was done by OWM data sourcers. Many PyOWM entity objects also carry `reception_time`, that is the UNIX timestamp when the entity object was created.

So, PyOWM is just giving you the value for `reference_time` as it is returned by the API - if the API sends back a wrong value (meaning: you expected that value to be referring to a different day of the week), the problem is on the API side and in that case I would suggest you to notify the API owners.

Also notice that before version 2.5 PyOWM used to provide datetime objects that were *not* timezone-aware. Is this your case?

Did I - at least partially - shed light on your doubt?

Also, FYI, instead of:

    datetime.datetime.fromtimestamp(int(weather.get_reference_time())).strftime('%A')

you can use

    weather.get_reference_time(timeformat='date').strftime('%A')

Cheers!

**Comment by lardconcepts** [comment]
Hi Claudio,

I'm still struggling with this from the perspective of a daily forecast. You see, for the first seven hours each day, the first item in the forecast object got from `for weather in f:` is yesterday's weather.

Here is the output of the forecast day of the first two days, done at 06:55 BST this morning, Monday:

```
<pyowm.webapi25.forecast.Forecast - reception time=2017-07-03 05:55:50+00, interval=daily>
2017-07-02 12:00:00+00
Sunday
Monday
```

The same is on the website, as you can see from the screenshots. (In fact, there is a little bit of caching so it took some minutes to change over). One screenshot is at 07:07 and shows yesterday as the first item, the next is 07:08 and now today is the first item.

Now, this is of course not a fault or bug with PyOWM or in any way your problem, but I was wondering if you could think of a smarter way to deal with it than what I am doing, which is to basically pull a four day forecast, and if the first day is not "today", then skip that first iteration.

Of course, it might be that I am missing an option already built into PyOWM but if not and you think "don't list yesterday's weather" might be a good option, let me know and I'll add it as a suggestion!

Thanks again for all your work on this.

![screenclip 69](https://user-images.githubusercontent.com/2894292/27787054-754477be-5fdb-11e7-8683-39abace18421.png)
![screenclip 68](https://user-images.githubusercontent.com/2894292/27787055-75491026-5fdb-11e7-8ce3-66fb77a4a569.png)

**Comment by csparpa** [comment]
Hi @lardconcepts I agree, this makes a lot of sense.

If I download *now* a weather forecast about a location, I should not get any data referring to a point in time before the current timestamp.
This means that PyOWM should - upon forecast data download - discard all weather data relating to the past.

I will open up an issue for this, thanks for notifying!
