### ISSUE TITLE
Language support doesn't work

### ISSUE THREAD

**Issue by TuxSeb** [csparpa/pyowm#251]
I have an issue when i'm trying to use French on pyowm, here's the the code:

```python
import pyowm
owm = pyowm.OWM(API_key='MY_API_KEY', language='fr')
observation = owm.weather_at_place('London,GB')
w = observation.get_weather()
print w
```
and here's the output: 
```python
<pyowm.webapi25.weather.Weather - reference time=2018-05-29 17:50:00+00, status=Haze>
```
What Pyowm is supposed to do when we use an other language ? shouldn't it print the French word for haze ? 

pyowm version: 2.8.0

thanks for your help

**Comment by csparpa** [comment]
Hi @TuxSeb thanks for pointing this out

I've checked out and it looks like everything works fine. When you call `print w` the weather's `status` property is printed but unfortunately that string is not translated by the OWM API

The reason is mentioned here: https://openweathermap.org/current :

![image](https://user-images.githubusercontent.com/5172190/40733537-2a1846b6-6436-11e8-8ce2-22d31521f118.png)

The NOTE says that only the `description` JSON field is returned in translation (in French in your case). That JSON field is then mapped by PyOWM onto the`detailed_status` field of class `Weather`

Just to counter check, please execute:

```python
import pyowm
owm = pyowm.OWM(API_key='MY_API_KEY', language='fr')
observation = owm.weather_at_place('London,GB')
w = observation.get_weather()
print w.get_status()
print w.get_detailed_status()
```

and you should get something like:

```shell
Haze
brume sèche
```

depending on the actual weather in London now.

But I do see your point: if one wants to print weather status in a certain language, why should that info be printed in English? 

I will augment the `Weather.__repr__` method with the detailed status so that the translated string is printed out

**Comment by TuxSeb** [comment]
Ok, thanks you !

**Comment by csparpa** [comment]
Fixed with https://github.com/csparpa/pyowm/commit/cceeb1a1fb6e64aa29c670e4dc92022a7f907c11
