### ISSUE TITLE
Problem with Agro manager

### ISSUE THREAD

**Issue by EveryoneInOne** [csparpa/pyowm#294]
Hi i installed pyown by pip for python 2.7 and i have problem with agro.manger
my code =import pyowm
from pyowm import OWM
from time import time
from pyowm import constants

owm = pyowm.OWM('**********', version='2.5')

mgr = owm.agro_manager()
and error
Traceback (most recent call last):
  File "I:/mmine/FILE/ADd_in/Ra/Install/WET.py", line 8, in <module>
    mgr = owm.agro_manager()
AttributeError: 'OWM25' object has no attribute 'agro_manager'

how to fix that ? thanks

**Comment by csparpa** [comment]
Hello @EveryoneInOne 

I suppose you installed PyOWM version 2.9 using pip (can you confirm?).... Be aware that **in such a version, there is NO support for Agro API** - this has been added in version 2.10 which unfortunately is not supported on Python 2

This is a project governance decision that I've taken in order to foster Python 3 adoption, as on January 1st 2020 Python 2 will be discontinued.

**So I'm sorry to say that you will need to switch to Python 3 and then use PyOWM 2.10 to use Agro API support** :-(

Please let me know, thanks

**Comment by csparpa** [comment]
Closing this as no further action is required
