### ISSUE TITLE
Set use_ssl to True as default

### ISSUE THREAD

**Issue by edenhaus** [csparpa/pyowm#303]
Ciao Claudio,

Nowadays the most traffic already is using https and I think we should activate it as default.
We are always sending our api key in our requests. What do you think?

Saluti dall'alto adige

**Comment by csparpa** [comment]
Ciao,

it seems very reasonable to me :)

Would you please modify that flag in the default configuration and run all tests (unit + integration) just to make sure everything works?
In particular, I'd check that the HTTP client library (`requests`) works as expected

Thank you very much!

PS: I'm literally craving for a trekking session in Alto Adige - it's been 3 years since the last one!!

**Comment by csparpa** [comment]
Fixed by #305
