### ISSUE TITLE
One Call History

### ISSUE THREAD

**Issue by grrodre** [csparpa/pyowm#314]
May I be wrong or not properly using it. But it seems that when using _one_call_history_ the returned dictionary use also _forecast_hourly_ key whereas the documentation gives hourly. That's a little confusing if it is really an historical data or a forecasted data.

`one_call = mgr.one_call_history(lat=52.52, lon=13.40)

one_call.forecast_hourly
`

https://github.com/csparpa/pyowm/blob/53370082a87a90a07a43c6a34fde83002795c89a/pyowm/weatherapi25/one_call.py#L94

**Comment by csparpa** [comment]
Hi @grrodre I agree with you, but that's exactly how the OWM One Call API works

It might be easier to think of One Call objects such as "photograhps" of observed+forecasted weather data, taken at a specific timestamp. So if you query for a photograph taken in the past, that photo carries forecasts that *might* still refer to the past, depending how deeply you go back in time when querying the photograph.

To make myself more clear:

```python

# this call retrieves One Call data for TODAY
one_call = mgr.one_call(lat=52.52, lon=13.40)

# this call retrieves One Call data for the day: TODAY - 5 DAYS (so it refers to a past day)
one_call_history = mgr.one_call_history(lat=52.52, lon=13.40)

one_call.forecast_hourly             # this is the hourly weather forecast (so it's in the future)
one_call_history.forecast_hourly     # this is the hourly weather forecast that was given 5 DAYS AGO (so it's in the past)
```

For the moment I'll update the docs so that doesn't sound so confusing

Thanks for pointing this out!

**Comment by grrodre** [comment]
Hello @csparpa and thank you for your detailed response. 

Your explanation make sense, however I think i expressed myself wrong. I meant the One Call API documentation and specific the https://openweathermap.org/api/one-call-api#history history one. 
The key here is _hourly_ whereas in pyowm is _forecast_hourly_. That lead me to confusion.

Regards.

**Comment by csparpa** [comment]
I see your point

IMO PyOWM uses a name ("forecast_hourly") that explains better the meaning of the data with respect to the one used by the JSON in the One Call API (they use "hourly"). So that would possibly be good - at least, improving the lack of semantics in the One Call API

Anyway, is it now clear what the forecasted data in OneCall objects mean ?

**Comment by csparpa** [comment]
@grrodre I assume this is OK. In case, pls open the issue again

**Comment by grrodre** [comment]
Ciao @csparpa . Thank for your message and sorry not to reply before.
I ended up using directly the api from openweathermaps. 

Regargs.
