### ISSUE TITLE
PYOWM module nor found random

### ISSUE THREAD

**Issue by tjerram** [csparpa/pyowm#355]
I have a python application that includes a file with pyowm as an include.  everything works fie most of the time but my application randomly fails with an error that says pyowm module not found.  The weird part is that the min application I am running doesn't use pyowm or any of the functions in the include file that require pyowm.  The include file works fine with other applications that do use the pyowm functions and they never seam to fail.  Any thoughts

**Comment by csparpa** [comment]
@tjerram you'll have a VERY hard time convincing me about errors randomly occurring WITHOUT providing any context/code of yours... :)

So please bring some evidence so we can debug!

**Comment by tjerram** [comment]
What would help?  I can send a copy of the syslog if that helps.  The
application is running continuously using nohup but nothing shows up in the
nohup.out log file.  All I see when I detect the error is an onscreen error
that says module pyowm not found.

It's a real mystery to me.  Any help would be appreciated.

Tom Jerram
(607) 235-0316

**Comment by csparpa** [comment]
Mmmm that looks weird

Usually a "module not found" error either means that the module is not installed or that Python can't manage to find it

So, just to understand (please confirm/amend):
  - your app is a sort of a server/loop that runs forever or is it a croned app ?
  - you import pyowm but don't use any of its functionality
  
Provided that the above points are confirmed, I have a few questions to help you & me debug:
  - do you import other third-party libraries into your app ?
  - what do you mean with "the min application I am running doesn't use pyowm or any of the functions in the include file that require pyowm" ? Can you provide the code structure of your app (eg. how modules are organized, what is the main include file you refer to, etc.) ?
  - can you please post the full error stack trace here?
  - what env/OS are you running your app on ?
  - how did you install PyOWM ? Is it installed into the "standard" path for third party Python libraries on your env/OS (if you installed it with `pip` you can check this with `pip show pyowm`) ?

With these info we can try to reason on some possible causes

Also, please try to print out the `PYTHONPATH` just before you import pyowm / the inlcude file that imports pyowm and check if it looks consistent across runs

As far as the `nohup.out` not reporting the error, that might be because your `stderr` is not redirected into it

Waiting for your answeres buddy
thanks

**Comment by tjerram** [comment]
Sorry to take a while to respond.  I deleted the pyowm import and
everything has run fine since.  So, my problem is solved but, I know it
does not solve the underlying questions.  I am afraid my limited skills
prevent me from investigating further.

Thanks for your response.

*Tom Jerram*

Tom@jerram.org
(607) 235-0316

**Comment by csparpa** [comment]
good! :) glad it works now
