### ISSUE TITLE
Support for max_retries when making call from requests

### ISSUE THREAD

**Issue by Monal5031** [csparpa/pyowm#381]
I was using pyowm when I came across this error:

```
[ERROR] InvalidSSLCertificateError: HTTPSConnectionPool(host='api.openweathermap.org', port=443): 

Max retries exceeded with url: /data/2.5/weather?<ids> 

(Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1091)')))
```

After looking through the code I found there is no option in config to set a `max_retries`.

I was hoping this support could be added by allowing a max_retries param in any config and using it to create a new Session/Adapter for requests before making the API calls here:

https://github.com/csparpa/pyowm/blob/master/pyowm/commons/http_client.py#L131

**Comment by csparpa** [comment]
Good catch! Thanks, this will fit into the next release :)

Would you like to submit a PR yourself for this ?

**Comment by Monal5031** [comment]
I can work on it @csparpa , although won't be able to complete it soon (I hope that's okay).

If someone else wishes to work on this, please let me know.

**Comment by csparpa** [comment]
Never mind @Monal5031 , I've submitted e3832d19b9c50bdb4bef9233899c0e85b2712e17 which should do the trick

By default, PyOWM will continue to apply infinite retries in calling the OWM API, but if you need to limit the number of calls this can be done via the configuration dict

By the way, in order to fix the `InvalidSSLCertificateError` you were getting, try to set `"verify_ssl_certs": False` in the config dict

**Comment by Monal5031** [comment]
Thanks @csparpa for fixing the issue so fast and also for the suggestion I'll try that (I however don't want to disable SSL verification) :)
