### ISSUE TITLE
One Call Minutely Forecast has blank Statuses

### ISSUE THREAD

**Issue by sopheset111** [csparpa/pyowm#383]
The One Call Minutely forecast has blanks for the Status and Detailed status. To make sure this wasn't a Geo-location issue I tried Hourly Forecast which when returned did have statuses. 
![1](https://user-images.githubusercontent.com/56524319/133422322-8a804ba5-fbc6-4475-a971-6cf6554501f9.PNG)

**Comment by csparpa** [comment]
@sopheset111 thanks for pointing this out

Does the issue still happen after a few days? What location were you calling it upon ?

**Comment by sopheset111** [comment]
Yes the issue does still happen after a few days and the location I was calling upon is a lat, long set at 48, -122

**Comment by csparpa** [comment]
Hello @sopheset111 I've checked it out

It seems like PyOWM is working as expected. The problem here is that the OWM web API is not returning any weather status for minutely forecasts, but it indeed does for hourly and daily ones

This can be seen from the returned JSON:

```json
{

  "lat":48,

  "lon":-122, 

  ...... , 

  "minutely":[

    {"dt":1632428100,"precipitation":0},
    {"dt":1632428160,"precipitation":0},
    .......
  ],

  "hourly":[

    {"dt":1632427200,"temp":291.46,"feels_like":291.17,"pressure":1027,"humidity":70,"dew_point":285.9,"uvi":4.1,"clouds":96,"visibility":10000,"wind_speed":2.33,"wind_deg":296,"wind_gust":2.42,"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"pop":0},
    {"dt":1632430800,"temp":291.67,"feels_like":291.3,"pressure":1026,"humidity":66,"dew_point":285.2,"uvi":3.84,"clouds":96,"visibility":10000,"wind_speed":3.14,"wind_deg":301,"wind_gust":3.13,"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"pop":0},
    ............... 
  ]

}

```

and also in the debugger:

![image](https://user-images.githubusercontent.com/5172190/134577141-8d9ed86c-15dc-4acc-9d72-d2026716c7a3.png)

There's not much I can do.

I'm not sure if this also happens upon different lat/lon couples
