### ISSUE TITLE
error 510 when executed from the crontab

### ISSUE THREAD

**Issue by BlackSailor** [csparpa/pyowm#69]
All works fine but I got following error when run it from the crontab:

File "/home/user/myapp/pyowm/commons/owmhttpclient.py", line 64, in call_API
raise api_call_error.APICallError(str(e.reason), e)
pyowm.exceptions.api_call_error.APICallError: Exception in calling OWM web API.
Reason: 
Caused by: HTTP Error 510:

**Comment by csparpa** [comment]
Hello, thanks for reaching out.
Usually 5xx errors mean errors on the server side. So, this would imply the API crashing somehow when you launch your request.
My suggestion is to retry again in a while: hopefully the API won't return a 510 any more.
If it still does, please post the full detail about your request and I'll take a look

**Comment by BlackSailor** [comment]
Thanks, script works like a charm when I execute it manually. Problem appear when script is executed from the crontab only. Here is the script:
http://pastebin.com/nk1U0NMi

**Comment by csparpa** [comment]
Mmmm... I've tried to run your script manually and it also works for me.

Can you please show me your cron expression?  What OS are you running on?

PS: in your script I see you instantia a LRUCache object but you don't actually use it. Are you aware of that? Take a look at [the docs](https://github.com/csparpa/pyowm/wiki/Usage-examples#owm-web-api-version-25-usage-examples)

**Comment by csparpa** [comment]
@BlackSailor I think I've got the answer.

If you take a look at this [thread](https://openweathermap.desk.com/customer/portal/questions/9787798-what-exactly-is-server-error-51-), you can see that HTTP status 510 when querying the OWM web API means that you've exceeded the max number of API calls per minute. That's because you are using an API key.

To be frank, it is not clear from the thread how many calls with the same API key are allowed per minute or per hour.

My advice is: don't use an API key, or - possibly - use a coarser periodicity for your cron job. Hope this helped out!

**Comment by BlackSailor** [comment]
@csparpa Thank you
