### ISSUE TITLE
Cannot query Antarctica weather

### ISSUE THREAD

**Issue by jdorleans** [csparpa/pyowm#94]
Antarctica weather response has sunset_time < 0 throwing an exception.

API Request:
http://api.openweathermap.org/data/2.5/weather?q=antarctica&units=metric&appid=2de143494c0b295cca9337e1e96b00e0

Exception occurs at:
https://github.com/csparpa/pyowm/blob/master/pyowm/webapi25/weather.py#L67

**Comment by csparpa** [comment]
@jdorleans thanks for notifying. I think this is something that needs to be fixed upstream, on the OWM API, as sunset_time is a UNIX timestamp and it makes no sense that it is < 0 !

So here nothing to patch on PyOWM in my opinion.

Do you agree?

**Comment by jdorleans** [comment]
Since PyOWM consumes a web service, it seems it does not make sense to put these kind of validation. However, supposing we have to manipulate and create the Weather object, it might be important to have them. Are those validated values used to do any calculus? If not, I believe those validations could be removed. If they are, then a workaround could be provided for this specific case. Does it make sense for you?

**Comment by csparpa** [comment]
Interesting point @jdorleans ! And I think you're right on it: if the OWM API says bullshit, then PyOWM should say bullshit too - this is naive consuming of a webservice.

But it would nevertheless be nice provide control on it to clients that use PyOWM objects: if they decide that having Weather objects with negative sunset/sunrise times or NaNs for any other value is fine, then they should be able to signal this to PyOWM - otherwise the default behaviour should be to allow any value returned by the API.

This could come as an additional feature on v3 - I added #97

Thanks for pointing this out: for the moment what we can do is to signal the issue on negative sunset/sunrise times to OWM API operators.
